TryGhost/gscan

Gruntfile.js
circle.yml
package.json

- added deployment script
- added test config

Add deployment script

---

public/css/gscan.css
public/js/gscan.js
tpl/index.hbs

refs #4
- watch file input and set submit button disabled property

Disable upload button if no file is selected

---

circle.yml

- updated circleCI version to 4.4.7

Use Node 4

---

circle.yml

- always use the latest version of node 4

Use latest node 4 version

---

lib/index.js

invent `options` for `checkZip` entrypoint.

feature: check zip options

---

package.json

This module is also flagged up as being insecure

⬆️ deps: node-uuid@1.4.7

---

lib/read-theme.js
package.json
test/general.test.js

closes #22 
- update regex for partial matching
- add sinon and rewire to make testing possible
- add tests

🐛 Fixes partial matching on windows

---

package.json

This release contains more dependency updates + a fix for partial resolution on windows.

⬆️ deps: express-hbs@1.0.3

---

package.json

Tested uploading some valid and invalid themes manual. Tests are green.
Bump Bluebird version to 3.4.6.
Not tested on windows.

⬆️  deps: bluebird@3.4.6

---

app/index.js
app/logging.js
app/middlewares/log-request.js
package.json

- ignition debug feature will work properly
- logging for gscan app
- better error handling

🛠  Ignition 1.0

---

lib/checks/001-deprecations.js
lib/checks/010-package-json.js
lib/format.js
test/001-deprecations.test.js
test/010-package-json.test.js

refs https://github.com/TryGhost/Ghost/issues/8222
- revert the other two options

✨  option: onlyFatalErrors for format function

---

lib/checks/001-deprecations.js

closes TryGhost/Ghost#8543
Fixes a bug, where the regex for deprecation checks was wrong because of the usage of `.` in the RegEx rather than `\.` 😔

🐛  Improve deprecation RegEx

---

lib/read-theme.js

- added `.svn` to the ignore list (same as `.git`)

Ignore `.svn` folders

---

lib/checks/005-template-compile.js

No Issue
- oops, reverting error of previous commit and registering partial

Register partial

---

lib/checks/001-deprecations.js
lib/spec.js
test/001-deprecations.test.js
test/fixtures/themes/001-deprecations/invalid/default.hbs
test/fixtures/themes/001-deprecations/invalid/partials/mypartial.hbs
test/fixtures/themes/001-deprecations/invalid/post.hbs
test/fixtures/themes/001-deprecations/mixed/default.hbs
test/fixtures/themes/001-deprecations/mixed/index.hbs
test/fixtures/themes/001-deprecations/valid/default.hbs
test/fixtures/themes/001-deprecations/valid/post.hbs
test/general.test.js

no issue
- Scans for the usage of `{{cover}}` with advice to change it to `{{cover_image}}`.
- Changes wording of `{{image}}` advice to not include `{{cover_image}}`
TODO:

👀  Scan for `{{cover}}` change `{{image}}` wording

---

lib/spec.js

no issue
Adds details for each rule incl. links to documentations and examples for the correct usage.
Todos:

📖  Error details in GScan

---

lib/checks/030-assets.js
lib/format.js
lib/read-theme.js
package.json
test/general.test.js

no issue
- Upgrading lodash from 3 to 4 is a bit involved
- Tried to search for all the things that have changed
- See https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings

⬆️ deps: Upgrade lodash 3.10.1 -> 4.17.4

---

.gitignore
.travis.yml
package.json

Active LTS starts in a couple of days.

Support Node v8

---

lib/spec.js

Change needed for pull request TryGhost/Ghost#8437

[i18n] t and lang added to knownHelpers

---

lib/index.js

Hi, would you be interested in some small PRs to update the syntax of files now
that Node v6 is the default?
Cheers

Update syntax of index file

---

package.json
yarn.lock

cc @kirrg001, @AileenCGN & @kevinansfield I'm moving us towards using these tools everywhere - much much simpler approach, I think.
- Run lint after tests
- Run tests before shipping
- Use yarn & git directly for shipping changes

🛠 Updated tooling to use new standards

---

lib/checks/001-deprecations.js
lib/specs/latest.js
test/001-deprecations.test.js
test/fixtures/themes/001-deprecations/latest/invalid/index.hbs
test/fixtures/themes/001-deprecations/latest/invalid_all/index.hbs
test/fixtures/themes/001-deprecations/latest/mixed/index.hbs
test/general.test.js

closes #129
- Added a check that detects the usage of `{{@blog.permalinks}}`, and creates a non-fatal error
- The recommendation is to remove the usage in the theme

✨ Added `{{@blog.permalinks}}` deprecation check

---

package.json
yarn.lock

This gets rid of all the vulnerabilities currently being reported by Github.

Update mocha and nodemon

---

lib/specs/latest.js
lib/specs/v1.js
test/001-deprecations.test.js
test/fixtures/themes/001-deprecations/latest/invalid/default.hbs
test/fixtures/themes/001-deprecations/latest/invalid_all/default.hbs
test/fixtures/themes/001-deprecations/latest/invalid_all/index.hbs
test/fixtures/themes/001-deprecations/latest/valid/index.hbs
test/general.test.js

closes #174
@ErisDS would love a review of error message wording for 2 new rules GS001-DEPR-BLG and GS001-DEPR-LNG. Thanks!

{{blog}} and {{lang}} helpers deprecation

---

lib/specs/latest.js
test/001-deprecations.test.js
test/fixtures/themes/001-deprecations/latest/invalid_all/post.hbs
test/general.test.js

refs #181
@ErisDS as usual wording check for new deprecation. Thank you :smiley:

✨ Added deprecation error for {{post.author_id}} property

---

lib/specs/latest.js
test/001-deprecations.test.js
test/fixtures/themes/001-deprecations/latest/invalid_all/default.hbs
test/general.test.js

refs #181
@ErisDS just a sanity check for the wording of the deprecation error code `GS001-DEPR-USER-GET`. Thanks!

✨ Added deprecation error for {{#get "user"}} helper

---

app/tpl/partials/rule-fail.hbs
app/tpl/result.hbs

refs https://github.com/TryGhost/Team/issues/206
- changed the overall style of the result page to improve readability

Updated results page styles

---

bin/cli.js
lib/format.js
package.json
test/general.test.js
yarn.lock

closes #210
@peterzimon small updates as described in the issue. Will merge these to start working on new groupings. Let me know if anything looks off :eyes:  
Default dark background terminal:
Light background terminal:

CLI output design refresh

---

bin/cli.js
lib/format.js
lib/specs/latest.js
lib/specs/v1.js
package.json
test/general.test.js
yarn.lock

closes #214
The output of the CLI check with `--verbose` parameter:

Verbose output option in CLI

---

lib/specs/v1.js
test/001-deprecations.test.js
test/fixtures/themes/001-deprecations/latest/invalid/default.hbs
test/fixtures/themes/001-deprecations/latest/invalid_all/default.hbs
test/fixtures/themes/001-deprecations/v1/invalid/default.hbs
test/general.test.js

supersedes https://github.com/TryGhost/gscan/pull/124
closes #123

{{each}} helper usage warning

---

app/tpl/index.hbs

refs #144
@peterzimon changes for the dropdown as discussed :wink: 	
Preview:

✨  Added "Canary" option to check against in web UI

---

lib/specs/v1.js

Tweaked it for grammatical reasons as well as adhering to our usage of "new"

Adjust wording

---

lib/specs/v2.js

@daviddarnes can has words :eyes: plz! danke!

💄Updated wording in rules using a specific version of Ghost

---

package.json

See https://www.npmjs.com/advisories/1065

Update dependency lodash to v4.17.12

---

lib/specs/v2.js

Added levels to all rules. #208

Fixed crash when rule level is missing

---

lib/specs/canary.js

refs https://github.com/TryGhost/Ghost/pull/11473

✨ Added price helper support

---

.travis.yml
package.json

🔥 Dropped Node v8 support

---

.github/deploy/Dockerfile
.github/deploy/k8s-deploy.yml
.github/workflows/deploy.yml

Added GitHub Action to auto-deploy GScan

---

lib/specs/canary.js
test/070-theme-translations.test.js

💡 Updated theme translation validity check to be fatal when failing

---

lib/ast-linter/helpers/index.js
lib/ast-linter/linter.js
lib/ast-linter/rules/base.js
lib/ast-linter/rules/index.js
lib/ast-linter/rules/lint-no-unknown-partials.js
lib/ast-linter/rules/mark-used-partials.js
lib/checks/005-template-compile.js
test/005-template-compile.test.js

:warning: WIP! :warning: 
refs https://github.com/TryGhost/Team/issues/774
- This is unfinished spike experimenting with AST parser. It is not fully working and the concept could be completely flowed as we have to privide additional state for the AST Linter

Added example spike tracking missing partials in code flows

---

README.md

Just a little fix for a mistake I noticed while browsing.

Remove an extra word from README.md

---

lib/ast-linter/rules/index.js
lib/ast-linter/rules/internal/scope.js
lib/ast-linter/rules/lint-no-author-helper-in-post-page-context.js
lib/specs/canary.js
test/090-template-syntax.test.js
test/checker.test.js
test/fixtures/themes/090-template-syntax/no-author-helper-in-post-context/no-post-context/default.hbs
test/fixtures/themes/090-template-syntax/no-author-helper-in-post-context/post-context/default.hbs
test/format.test.js

refs https://github.com/TryGhost/Toolbox/issues/241
Rule to detect and error when `{{author}}` helper is used in `{{post}}` context

✨ Added {{author}} helper deprecation check

---

lib/ast-linter/rules/index.js
lib/ast-linter/rules/internal/scope.js
lib/ast-linter/rules/lint-no-monthly-price-helper.js
lib/ast-linter/rules/lint-no-tier-benefit-as-object.js
lib/ast-linter/rules/lint-no-tier-price-as-object.js
lib/specs/canary.js
test/090-template-syntax.test.js
test/checker.test.js
test/fixtures/themes/001-deprecations/v5/invalid_all/post.hbs
test/fixtures/themes/090-template-syntax/no-monthly-price-helper/default.hbs
test/fixtures/themes/090-template-syntax/no-tier-benefit-as-object/default.hbs
test/fixtures/themes/090-template-syntax/no-yearly-price-helper/default.hbs
test/format.test.js

refs https://github.com/TryGhost/Ghost/issues/14881
closes https://github.com/TryGhost/Team/issues/1648
- Adds deprecation for the {{monthly_price.*}} helper use in favor of {{price}} helper in combination with {{@member.subscriptions}}

Added {{monthly_price.*}} helper deprecation

---

lib/specs/canary.js

- Updating rules in line with suggestions from @royalfig
These are Ryans suggested changes

Updated copy for some confusing rules

---

lib/specs/canary.js

refs https://github.com/TryGhost/Team/issues/1667

✨ Added total_members and total_paid_members support

---

lib/checks/110-page-builder-usage.js
lib/specs/canary.js
test/110-page-builder-usage.test.js
test/format.test.js

no refs
- added page checks back
- removed labs feature flag

Reimplemented page checks

---

lib/checks/110-page-builder-usage.js
lib/specs/canary.js
test/110-page-builder-usage.test.js

no refs
- point to new doc
- add file

Updated page check error messages

---

lib/specs/canary.js
test/format.test.js

no refs
- upgraded check 110 to error so it displays in ghost production

Updated check 110 to error

---

lib/checks/110-page-builder-usage.js
lib/specs/canary.js

refs https://github.com/TryGhost/Ghost/issues/17745, refs TryGhost/Ghost#17777
- more clearly indicated that a Ghost update is necessary
- specify that the @page use is specific to the beta editor at this time

Updated @page error messages

---

lib/read-theme.js

Refactored code for https://github.com/TryGhost/Ghost/issues/14882
Removed bluebird Promise from read-theme.js file

Removed Bluebird from `read-theme.js`

---

lib/checker.js

Refactored code for https://github.com/TryGhost/Ghost/issues/14882
Removed bluebird `Promise.reduce` from checkers.js file

Removed Bluebird `Promise.reduce` from `checker.js`

---

lib/checks/010-package-json.js
lib/specs/canary.js
package.json
test/010-package-json.test.js
test/fixtures/themes/010-packagejson/invalid-custom-theme/package.json
yarn.lock

refs https://github.com/TryGhost/Product/issues/3717

✨ Added rules for custom theme setting visibility

---

lib/checks/010-package-json.js
test/fixtures/themes/010-packagejson/invalid-custom-theme/package.json

refs https://github.com/TryGhost/Product/issues/3969

Increased the number of custom theme settings to 20

---

lib/specs/canary.js

refs https://github.com/TryGhost/Product/issues/4014
- these two helpers has been added as part of the Recommendations project

Added {{recommendations}} and {{readable_url}} to known helpers

---

package.json
yarn.lock

Updated @tryghost/nql to v0.12.0

---

.github/workflows/ci.yml
lib/specs/v4.js

ref ENG-809
ref https://linear.app/tryghost/issue/ENG-809
The rule was updated, but the error message wasn't

Fixed error message for custom theme settings

---

lib/specs/canary.js
test/080-helper-usage.test.js
test/checker.test.js
test/fixtures/themes/080-helper-usage/v5/invalid-no-empty-translations/assets/my.css
test/fixtures/themes/080-helper-usage/v5/invalid-no-empty-translations/author.hbs
test/fixtures/themes/080-helper-usage/v5/invalid-no-empty-translations/default.hbs
test/fixtures/themes/080-helper-usage/v5/invalid-no-empty-translations/error.hbs
test/fixtures/themes/080-helper-usage/v5/invalid-no-empty-translations/index.hbs
test/fixtures/themes/080-helper-usage/v5/invalid-no-empty-translations/package.json
test/fixtures/themes/080-helper-usage/v5/invalid-no-empty-translations/partials/mypartial.hbs
test/fixtures/themes/080-helper-usage/v5/invalid-no-empty-translations/post.hbs
test/fixtures/themes/080-helper-usage/v5/valid/assets/my.css
test/fixtures/themes/080-helper-usage/v5/valid/author.hbs
test/fixtures/themes/080-helper-usage/v5/valid/default.hbs
test/fixtures/themes/080-helper-usage/v5/valid/error.hbs
test/fixtures/themes/080-helper-usage/v5/valid/index.hbs
test/fixtures/themes/080-helper-usage/v5/valid/package.json
test/fixtures/themes/080-helper-usage/v5/valid/partials/mypartial.hbs
test/fixtures/themes/080-helper-usage/v5/valid/post.hbs

ref https://linear.app/tryghost/issue/SLO-182
- if the translate helper is used without a key, return a non-fatal error
- examples: `{{ t }}`, `{{ t '' }}`, `{{ t "" }}`

Added "GS080-NO-EMPTY-TRANSLATIONS" rule

---

lib/checks/090-template-syntax.js

Ref: https://linear.app/tryghost/issue/ENG-1444/gscan-slow-checking-for-themes-with-many-files

Added caching for checking partials 

---

README.md

Additions to the Development section of the readme.  I spent a couple minutes scratching my head about what 'yarn start' was doing, because I usually just use this package on the command line.  Maybe this will save the next person some time.

readme improvement for new devs

---

lib/checks/051-custom-fonts-css-properties.js
lib/specs/canary.js
test/051-custom-fonts-css-properties.test.js
test/fixtures/themes/051-custom-fonts-css-properties/missing/default.hbs
test/fixtures/themes/051-custom-fonts-css-properties/valid/assets/my.css
test/fixtures/themes/051-custom-fonts-css-properties/valid/default.hbs
test/format.test.js

Added GS051 rules for custom heading and body fonts

---

README.md
bin/cli.js
lib/checks/010-package-json.js
lib/specs/v6.js
lib/utils/versions.json
test/001-deprecations.test.js
test/010-package-json.test.js
test/050-koenig-css-classes.test.js
test/051-custom-fonts-css-properties.test.js
test/060-js-api-usage.test.js
test/080-helper-usage.test.js
test/090-template-syntax.test.js
test/110-page-builder-usage.test.js
test/120-no-unknown-globals.test.js
test/checker.test.js
test/format.test.js

- This has no new rules just yet
- This adds full support for v6 as the new canary version
- Including massive test coverage which is probably unnecessary!
- We need to be able to support the new version going forward, so this is pure prep

Added support for v6

---

README.md
app/tpl/index.hbs
lib/utils/versions.json
test/checker.test.js

no issue
Makes it so v6 is the default Ghost version checked

Updated default Ghost version check to v6
