tpl/default.hbs
Make the downloads link absolute to ghost.org so that it will link correctly from anywhere
=> Fix downloads link

public/js/gscan.js
`gscan.ghost.org` has a javascript error after uploading the theme. That's why its not possible to click the button `show the details`.
```
gscan.js:48 Uncaught TypeError: Cannot read property 'files' of undefined
```
=> fix: disable upload button on document ready event

lib/index.js
If we pass an object into `checkObject`, the fn itself modifies the original object.
=> fix: clone zip object because we modify the reference

lib/read-zip.js
When using `gscan` as a lib, it creates a `tmp` folder of the root project - that is annoying, because its just temp data. So we use the official tmp folder from `os`.
From the docu:
`The os.tmpdir() method returns a string specifying the operating system's default directory for temporary files.`
=> use official tmp dir function from node

lib/checks/010-package-json.js, lib/spec.js, test/010-package-json.test.js
closes #15
- change the level from error to warning on the package.json rules
- this is wrong, but matches the current behaviour of Ghost
=> 🐛 All package.json errors should be warnings

package.json
* https://nodesecurity.io/advisories/106
* older express depended on older accepts which required vulnerable negotiator 
* See PRs for context
* https://github.com/jshttp/negotiator/commit/26a05ec15cf7d1fa56000d66ebe9c9a1a62cb75c
* https://github.com/expressjs/express/pull/3006
=> Update express for negotiator RegExp DoS

package.json
* https://nodesecurity.io/advisories/minimatch_regular-expression-denial-of-service
* older express-hbs depended on older readdirp which required vulnerable minimatch 
* See PRs for context
* https://github.com/thlorenz/readdirp/pull/43
* https://github.com/barc/express-hbs/pull/103
Stops NPM complaining and stops my vulnerability detector going off on my Ghost server 👍
=> Update express-hbs for minimatch RegExp DoS

lib/format.js, lib/spec.js
These two little fixes will allow us to downgrade the asset helper rule to a warning. 
Merging this is dependent on us having some UI changes ready in Ghost: see #7367 and #7362
=> Convert the asset helper rule to a warning + provide rule codes in results

lib/read-theme.js, test/general.test.js
closes #43
- always make theme path absolute
- remove file if filename in ignored list and theme path in tmp directory
- ignore file if filename in ignored list and them path not in tmp directory
From my understanding of the `gscan` module, these are the possible use cases and the code branches they are expected to take:
1) CLI mode & path to a folder
=> ignore files & check theme
2) CLI mode & path to a ZIP file
=> extract to tmp directory, remove ignored files & check theme
3) Web interface mode & upload ZIP file
=> extract to tmp directory, remove ignored files & check theme
4) Lib mode & path to a folder (e.g: Ghost's validate theme feature)
=> ignore files & check theme
5) Lib mode & path to a ZIP file (e.g: Ghost's upload theme feature)
=> extract to tmp directory, remove ignored …
=> 🐛 Fixes ignored file removal by making it conditional to tmp directory

app/middlewares/log-request.js, lib/read-zip.js, package.json
Hi there,
This week a new version of the [uuid](https://github.com/kelektiv/node-uuid) module got released. The old module which was available by the name [node-uuid](https://www.npmjs.com/package/node-uuid) got deprecated and will show error message upon every install of the module.
To get rid of those install errors I've created this **automated pull request**. I've run some checks against your code base to test whether you're using one of the [deprecated apis](https://github.com/kelektiv/node-uuid/commit/5ae7287fc935eb55ef39133e4be17ef623ca000e), but this isn't the case.
Please test the changes against your code. I didn't run any tests and therefore can't guarantee that it isn't breaking. You can also just close this pr if you don't want to update your module.
In case there's already …
=> Update uuid to version 3.0.0

lib/spec.js
refs https://github.com/TryGhost/Ghost/issues/8348
**It's time to release gscan 1.0.**.
Alternatively we could support both image and img_url helper, but that is a little unclear and dirty?
If this PR get's merged, we have to support/release two different gscan versions.
Master will be the newest changes (=== 1.x)
=> 🔥  ✨  rename known helpers: image -> img_url

test/fixtures/themes/001-deprecations/invalid/default.hbs, test/fixtures/themes/001-deprecations/invalid/partials/mypartial.hbs, test/fixtures/themes/001-deprecations/valid/default.hbs, test/fixtures/themes/001-deprecations/valid/partials/mypartial.hbs
no issue
Adds wrong usage cases for deprecation checks to prove that they won't be detected and therefore don't cause errors.
=> 🐷  Add more test cases for deprecation usage

lib/checks/001-deprecations.js, lib/read-theme.js, test/fixtures/themes/001-deprecations/valid/partials/this-is-a-very-long-path.hbs.old
The regex to filter hbs files is written in a way that it can create a
condition where gscan will hang forever. This is similar to an endless
loop and not handled with an exception in JS Regex. This condition is
also referred to as „catastrophic backtrack“.
Pre Condition:
- hbs and a second extension (e.g.: .hbs.old)
- part of the partials folder
- relatively long filename/filepath (> 35 chars)
Changes:
- changed/optimized regex
- added test file to reproduce the case
=> Regex hangs

lib/read-theme.js, test/general.test.js
Extension parsing doesn’t use the last part of the extension but
everything that follows after a dot.
Example - logo.new.hbs
- old: .new.hbs
- new: .hbs
Changes:
- changed to only use numbers and characters after a dot as file
extension
- added `i` to make regex case insensitive
- added test
=> Fix extension parsing

lib/checks/005-template-compile.js, lib/faker/index.js, test/005-template-compile.test.js, test/fixtures/themes/005-compile/invalid/author.hbs
closes #63
- provides fake data to allow author/post/tag blocks to execute
- uses handlebars {{each}} helper to replace {{foreach}} helper
=> Provide fake data to hbs compiler

lib/checks/002-comment-id.js, lib/spec.js, test/general.test.js
See https://github.com/TryGhost/Ghost/issues/8760 for the reasoning behind these additional checks.
Here's my regex101 test ground for the  regex which looks for the Disqus embed: https://regex101.com/r/AFj5Ml/3
- Ghost 1.0 changed id format from integers to ObjectID strings
- This breaks disqus comments 😞
- We're rolling out an emergency workaround to use `{{comment_id}}` instead
- This will contain the old id for posts that get migrated from LTS
- Anyone using the disqus embed MUST update their theme in order to keep comments
- Anyone using `{{id}}` MAY also want to switch over to the new property
=> 🚨 Add checks for {{id}} and disqus embeds

lib/spec.js
refs #78
- the id helper regex is too general and detects all {{id}} usages (e.g. in get helper usages)
- there is no quick way to modify the existing regex to cover all cases or we could cover some cases, but there is a risk to run into more edge cases and then have to spend time again fixing them
- downgrading it to a recommendation is the easiest way for now
- recommendations should only appear on gscan.ghost.org
=> 🎨  downgrade id helper detection to recommendation

lib/checks/010-package-json.js, lib/spec.js, test/010-package-json.test.js, test/fixtures/themes/010-packagejson/bad-config-2/package.json, test/fixtures/themes/010-packagejson/bad-config/package.json, test/fixtures/themes/010-packagejson/valid/package.json
Requires #81 
no issue
- Requires lodash upgrade as _.isNil was added in v4
- Posts per page needs to be a number > 0
- Simplified the logic around posts_per_page
- Ensuring this is validated properly allows us to remove some logic from Ghost
=> ✨ Tweaked ppp spec to include being > 0 

package.json
no issue
- We commonly use `npm run dev` to start in development mode
- Adds nodemon as a dependency (we already have nodemon config in the repo)
=> 🛠 Updated npm scripts to match other projects

lib/spec.js
Was added in [Ghost 1.13.0](http://themes.ghost.org/docs/changelog#section-ghost-1130)
=> Add reading_time helper to list of known helpers

.travis.yml, package.json
no issue
- https://github.com/nodejs/Release
- disable running Node v4 tests in travis
- added engine to package.json `>=6`
=> 🔥 Drop Node v4 support

README.md
There was a typo in the command-line for the npm installation, it was enough to break it for me, the correct option is a lower-case g. Simple fix, might help someone, definitely won't break anything.
=> Fixed the command line for installing gscan globally with npm

app/tpl/index.hbs, lib/spec.js
closes #117
- replaced https://themes.ghost.org/docs/ with https://themes.ghost.org/v1.25.0/docs/
=> Update links to docs to last major version

README.md, app/tpl/result.hbs, bin/cli.js, lib/checker.js
refs #116
needs #127
- uses the versions util to fetch the major version and pass it along our `theme` object
- outputs the tested version for CLI and App usage
- for module usage, GScan returns a `checkedVersion` property with the major version that it was checked for
- updated README to include version usage
=> Output the major version that was checked

lib/checks/010-package-json.js, lib/checks/020-theme-structure.js, lib/checks/030-assets.js, lib/checks/040-ghost-head-foot.js, lib/format.js, test/010-package-json.test.js, test/020-theme-structure.test.js, test/030-assets.test.js, test/040-ghost-head-foot.test.js, test/general.test.js
refs #122
- gscan.format accepts a new flag to return a different format
- sort by errors & warnings files
**This PR does not sort the passed rules by files, because we never push the reference and this is too much work now**
=> ✨ Added ability to sort by files

lib/checks/010-package-json.js, lib/specs/latest.js, test/010-package-json.test.js, test/fixtures/themes/010-packagejson/fields-are-invalid/package.json, test/fixtures/themes/010-packagejson/fields-are-valid/package.json, test/general.test.js
closes #143 
This is being added as a warning in Ghost 2.0, and will be an error in Ghost 3.0
-----
~~Tests are failing unexpectedly saying that the new rule is present in the list of passes/fails when it should not be, e.g. for `checks for an older version if passed`~~
Tests fixed by https://github.com/TryGhost/gscan/commit/64e39ec344b26a771a080a42092c1fe2ffe64489 working on adding new tests for this change.
=> ✨Added keyword check for `ghost-theme`

lib/checks/001-deprecations.js, lib/checks/002-comment-id.js, lib/checks/005-template-compile.js, lib/checks/020-theme-structure.js, lib/checks/040-ghost-head-foot.js, lib/checks/050-koenig-css-classes.js
closes #140
- Instead of listing all rules per checker again, we read them with a regex from the spec
- 030 assets check is currently the only check with the two rules hard coded
=> Refactor checkers to fetch rules per name

bin/cli.js
Note: This PR is instead of https://github.com/TryGhost/gscan/pull/108
I tried to cleanup that PR but I could not get it to work for me. This change is a little bit simpler and can probably be improved upon.
If there is an error or a warning, we exit with code 1. Else with code 0. 
I show a summary message at the end.
You can see this PR working in Casper:
[with a deliberate error](https://travis-ci.org/ErisDS/Casper/builds/415992710)
[with a deliberate warning](https://travis-ci.org/ErisDS/Casper/builds/415992587)
[travis branch off of 2.0 branch is passing](https://travis-ci.org/ErisDS/Casper/builds/415991831)
closes #105
- Show exit code 1 if there are any errors or warnings
- We show this for warnings because warnings are still things that should be fixed e.g. will be errors in the …
=> ✨ Added exit code to CLI for programmatic usage

lib/specs/latest.js, test/fixtures/themes/001-deprecations/v1/invalid/post.hbs
no issue
- {{author}} is an output helper and it should be replaced with {{authors}} (not with {{primary_author}}, because this is not an output helper, it's an object)
- {{#author}}{{/author}} should be replaced with {{#primary_author}} or {{#foreach authors}}..
- update rule texts to use "is deprecated" instead of "is not valid anymore"
=> 🎨 Optimised GScan rule messages

lib/checks/050-koenig-css-classes.js, test/fixtures/themes/050-koenig-css-classes/mixed/assets/my.css, test/fixtures/themes/050-koenig-css-classes/mixed/default.hbs
closes #152
- Scan through every file to find required Koenig CSS classes instead of `*.css` files only
- Udated test to proof detection
=> 🐛 Fixed Koenig CSS detection in non-CSS files

lib/checks/050-koenig-css-classes.js, test/050-koenig-css-classes.test.js
closes #159
- the checker read any asset from disk
- added restriction for .hbs and .css files
=> 🐛 Fixed GScan performance

bin/cli.js, package.json, yarn.lock
closes #177
@ErisDS one thing that bothers me with new output for usage:
```
Usage:
gscan <themePath> [options]
Arguments:
<themePath>  Theme folder or .zip file path                                    [required] [string]
Global Options:
-h, --help     Show help                                                [commands: help] [boolean]
-v, --version  Show version number                                   [commands: version] [boolean]
Options:
-p, --pre  Run a pre-check only                                                          [boolean]
-z, --zip  Theme path points to a zip file                                               [boolean]
-1, --v1   Check theme for Ghost 1.0 compatibility, instead of 2.0                       [boolean]
```
is that `Options:` part, that the user would be most …
=> 🛠 Ported cli to use pretty-cli

package.json, yarn.lock
Fixes potential RCE https://github.com/wycats/handlebars.js/blob/v4.1.2/release-notes.md#v412---april-13th-2019
=> Updated express-hbs to 1.1.1

lib/checks/010-package-json.js, lib/specs/canary.js, test/010-package-json.test.js, test/fixtures/themes/010-packagejson/fields-are-valid/package.json
refs #144
Added warning about fallback to v3 of `ghost-api` engine in the canary set of rules.
=> ✨ Added pakcage.json "ghost-api" warning rule in canary

lib/specs/v2.js
refs #144
- Updates wording for {{#get "users"}} helper which will no longer return any data
=> 💄 Updated wording for get users helper

lib/checks/010-package-json.js, lib/specs/canary.js, test/010-package-json.test.js, test/fixtures/themes/010-packagejson/fields-are-invalid/package.json
refs #144
TODO: 
- A: only detect v0.1 detection
=> ✨ Added rule in canary set for ghost-api=v0.1 detection

lib/specs/canary.js, test/001-deprecations.test.js, test/fixtures/themes/001-deprecations/canary/invalid/default.hbs, test/fixtures/themes/001-deprecations/canary/invalid/error.hbs, test/fixtures/themes/001-deprecations/canary/invalid_all/default.hbs, test/fixtures/themes/001-deprecations/canary/invalid_all/error.hbs, test/fixtures/themes/001-deprecations/canary/valid/default.hbs, test/fixtures/themes/001-deprecations/canary/valid/error.hbs
refs https://github.com/TryGhost/gscan/issues/144
refs https://github.com/TryGhost/gscan/issues/137
- Overridden GS001-DEPR-ESC v2 rule in canary set
- The original {{statusCode}} deprecation (#137) was a mistake and what was meant to be deprecated is {{code}} (ref. https://github.com/TryGhost/Ghost/pull/9144/files#diff-6b41d6f0ef148f7d202931a87d5c4130R85)
- `statusCode` was meant to be used everywhere similarly to this change - https://github.com/TryGhost/Ghost/commit/02199c6b02589b12324d8191c69ea80aad6b907a
=> 💡️Corrected error.statusCode rule to deprecate error.code instead

lib/specs/v2.js, test/050-koenig-css-classes.test.js, test/fixtures/themes/050-koenig-css-classes/valid/assets/my.css, test/general.test.js
refs https://github.com/TryGhost/Ghost/pull/11024
- 10 bookmark card rules have landed in Ghost as of 2.30.0 release, so they need to be checked for in v2 onwards
@kevinansfield would appreciate if you could double-check if all needed styles are correct.
@daviddarnes lets colab on the words used in these rules :dancer: will also apply similar wording to other CSS rules.
Things to keep in mind for wording:
- should not be Ghost version specific (e.g. use Ghsot 2.0)
- say exactly what will break
=> ✨ Added Koenig bookmark card CSS v2 rules 

lib/specs/canary.js, lib/specs/v2.js, test/001-deprecations.test.js, test/fixtures/themes/001-deprecations/v2/invalid_all/default.hbs, test/fixtures/themes/001-deprecations/v2/invalid_all/error.hbs, test/general.test.js
refs #144
- This rule was not meant to be there in the first place and might cause confusion for people who check if their v3 theme is running with Ghost v2 properly
=> Removed missleading rule for {{statuscode}} in v2 rules

app/tpl/index.hbs, lib/checker.js, test/general.test.js
closes #144 
Changes default checked version to what is currently a `canary` set of rules.
=> V3 To be merged with Ghost 3.0

lib/specs/index.js, test/001-deprecations.test.js, test/checker.test.js, test/format.test.js
=> 🐛 Fixed default checks not being run on canary rules

lib/read-zip.js
no issue
Disables the alphabetical sorting, which makes sure the paths are sorted from shortest to highest number of sub-folders.
=> 🐛 Removed file sorting in zip reading

lib/specs/canary.js, test/001-deprecations.test.js, test/checker.test.js, test/fixtures/themes/001-deprecations/canary/invalid_all/default.hbs, test/fixtures/themes/001-deprecations/v3/invalid_all/default.hbs, test/format.test.js
refs https://github.com/TryGhost/Team/issues/492
:warning: WIP: needs:
Ghost 4.0 sets labs.members flat to always be "true" by default and will remove the property completely (resolving it ot "false") starting with next version - Ghost 5.0
=> 💄 Added new check for {{@labs.members}} helper use

lib/checks/010-package-json.js
issue https://github.com/TryGhost/Team/issues/706
This reduces parsing time as node doesn't need to parse the whole validator.js library.
```
hyperfine --warmup 3  --min-runs 30 '/Users/thibautpatel/.nvm/versions/node/v14.17.0/bin/node bin/cli.js ../Casper'
Benchmark #1: /Users/thibautpatel/.nvm/versions/node/v14.17.0/bin/node bin/cli.js ../Casper
Time (mean ± σ):     464.4 ms ±   8.3 ms    [User: 491.5 ms, System: 79.2 ms]
Range (min … max):   453.6 ms … 495.5 ms    30 runs
```
```
Benchmark #1: /Users/thibautpatel/.nvm/versions/node/v14.17.0/bin/node bin/cli.js ../Casper
Time (mean ± σ):     443.8 ms ±   6.0 ms    [User: 478.0 ms, System: 74.3 ms]
Range (min … max):   433.5 ms … 461.6 ms    30 runs
```
So this is approximately 20ms shaved from an unzipped gscan check.
=> Only load the `isEmail` function from the validator library

lib/checker.js, lib/index.js
refs https://github.com/TryGhost/Team/issues/1070
- added `allowMatchHelper` option to `check()` and `checkZip()` methods
- when option is true, manually push `match` to the allowed helper list
=> Added match helper to allowed list when labs feature is enabled

lib/read-theme.js, test/fixtures/themes/theme-with-custom-settings-packagejson/package.json, test/read-theme.test.js
refs https://github.com/TryGhost/Team/issues/1070
- pass `options` from `check()` and `checkZip()` through to `readTheme()` so the labs flags are available where needed
- when `labs.customThemeSettings === true`, inside `readTheme()` read `package.json` and add a `customSettings` property to the theme object returned by `check()` and `checkZip()`
=> Exposed custom theme settings read from package.json

lib/ast-linter/rules/base.js, test/fixtures/themes/005-compile/canary/invalid-with-partials/index.hbs, test/fixtures/themes/005-compile/canary/valid-with-partials/index.hbs, test/fixtures/themes/005-compile/v1/invalid-with-partials/index.hbs, test/fixtures/themes/005-compile/v2/invalid-with-partials/index.hbs, test/fixtures/themes/005-compile/v3/invalid-with-partials/index.hbs, test/fixtures/themes/005-compile/v3/valid-with-partials/index.hbs, test/fixtures/themes/theme-with-partials/index.hbs
Adding support to `isValidPartialReference` check in the AST Linter for the [Handlebars-provided partial `@partial-block`](https://handlebarsjs.com/guide/partials.html#partial-blocks).
Previously the check only compared a node's name against the list of partials defined in the theme's `partials/` directory; have added a static reference to `@partial-block` to be included in this list without requiring it to be present in that directory.
=> Validation Support for @partial-block

lib/checks/001-deprecations.js
fixes fatal error that results in status 500 errors when theme includes a file that ends in /[^.].hbs/
also fixes that theme fails to activate of theme includes files ending in /[^.].hbs/
Example/to reproduce error: 
Create new theme, and create new file amp.__hbs. 
Observe that ghost crashes if theme is already in use, else theme can't be activated (not error is displayed).
Upon inspecting ghost logs, observe fatal crash in line 26 (`if (themeFile.content.match(check.regex))`) "Cannot read property 'match' of undefined".
This is because content only exists for actual hbs templates and a file ".__hbs" has not been processed as a template.
This change fixes the regex to detect `.hbs` and only `.hbs`
Background: I ran into exactly above described scenario - I wanted to temporarily disable …
=> fix ghost crash "Cannot read property 'match' of undefined"

lib/checks/030-assets.js, lib/read-theme.js, test/checker.test.js, test/read-theme.test.js
- `lstatSync` is a blocking call to the filesystem and may block the
process when the underlying filesystem is slow
- by this point in the code, we've already done async lstat calls once
because we've traversed the theme folder to find and load the files
- so basically, we're doing superfluous blocking calls for the fun of it 🙈
- this commit adds the necessary data re: symlinks into the list of
files we initially build up, alters the code to use this data and
removes the blocking calls
=> Removed blocking lstat calls

lib/specs/canary.js
Should be 'total_paid_members' rather than 'total_paid_memberss'?
=> Too many S's

lib/specs/canary.js
refs https://github.com/TryGhost/Team/issues/1695
This is needed so that we are able to use the helper in themes
=> Added comment_count to known helpers

.github/workflows/check-links.yml, package.json, test/valid-doc-links.js, yarn.lock
no issue
Added a little test to extract the links in the `details` property of a rule. Not part of the official test suite since it hits `ghost.org` a bunch.
- Configured to run weekly
- Can also be manually triggered
This is a very basic starting point that can be expanded as needed 😊
Things it does:
- Ensure `a` tag has a link, and that link points to a WHATWG-compliant URL
- Ensure `a` tag contains `target="_blank"`
- Ensure links point to a `ghost.org` site
- Ensure links are not redirected (non-fatal)
- Ensure IDs referenced in a link are valid
- self-rate-limits (5 URLs / 150ms right now)
Things it doesn't do:
- Tell you where a link was redirected
- Dedupe rule list - we could get away with only handling new rules of a test suite, but I didn't want to change existing files in this …
=> Added workflow to check links in docs

bin/cli.js
Ref #465 
When passing a zip file to gscan without including the `-z` flag, gscan currently quits without logging the error, which is confusing to users.
This change logs the error to the console, and, if the error is because the path passed is not a dir, then provides a hint about the `z` flag.
=> update error msg when passing zip without flag

lib/ast-linter/rules/internal/scope.js, lib/ast-linter/rules/lint-no-unknown-globals.js, lib/checks/120-no-unknown-globals.js, test/120-no-unknown-globals.test.js, test/fixtures/themes/120-no-unknown-globals/v5/invalid/default.hbs, test/fixtures/themes/120-no-unknown-globals/v5/valid-with-locals/default.hbs
- log error for each bad reference instead of one per file
- move to top-level global checking (less specific for the moment)
- add all data variables in lieu of checking within foreach loop
=> Update globals check

lib/read-zip.js
Removed unused bluebird Promise import from read-zip.js for https://github.com/TryGhost/Ghost/issues/14882
=> Removed unused bluebird Promise import from read-zip.js

lib/ast-linter/rules/mark-used-partials.js, lib/checks/005-template-compile.js, lib/checks/090-template-syntax.js, lib/checks/100-custom-template-settings-usage.js, lib/checks/110-page-builder-usage.js, lib/checks/120-no-unknown-globals.js, lib/read-theme.js, test/checker.test.js, test/read-theme.test.js
fixes https://github.com/TryGhost/DevOps/issues/3
- for themes with many files and partials, the checks can take a very long time to run
- digging into it, it seems that this is due to the `normalizePath` function being executed tens of thousands of times over the same strings
- I tried optimizing the function but it wasn't easy, so the next best step is to precalculate the normalized paths when loading the theme, and then they're ready to go next time
- this optimizes the check time of a particularly heavy theme from 5s to 1.7s on my local machine, and I bet slower machines get a bigger improvement
=> Precalculated normalized file names to optimize performance

lib/checks/100-custom-template-settings-usage.js, lib/checks/110-page-builder-usage.js
refs https://github.com/TryGhost/gscan/commit/0f0b0628c1f9f4ce6d92f3ae258402e5547d2c17
- this adds partial caching, similar to the commit above, so we don't perform unnecessary work in GScan theme checking
=> Added partial caching to GS100 and GS110 rules

lib/checker.js, test/checker.test.js
no issue
- in some scenarios we want to read a theme's structure quickly and don't care about running the full suite of checks
- added `skipChecks` option that bypasses the heavier checks
- does not skip the linter based checks because those are currently coupled with theme reading
=> Added skipChecks option to check function

lib/specs/canary.js, test/fixtures/themes/005-compile/v5/valid/default.hbs
Added these two keys to the list of known helpers for v5.
Added them into a fixture theme for test coverage [for the error that they were triggering] but would welcome suggestions on a better test structure.
=> Add support for content_api_url and content_api_key helpers

app/index.js, app/middlewares/sentry.js
- Sentry.Handlers.requestHandler() and Sentry.Handlers.errorHandler() are no longer available
- Initializing and importing Sentry should be enough from now on
=> Made Sentry middleware compatible with version 9
